const state = { mode:'exam', index:0, answers:{}, flags:{}, started:false, submitted:false, remaining:5400, timer:null, questions:[...ENGLISH_BANK] };
const $ = (s) => document.querySelector(s);
const letters = ['A','B','C','D','E','F'];
function escapeHtml(s){ return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function renderHome(){
  clearInterval(state.timer); state.started=false;
  $('#app').innerHTML = `<header class="top"><div class="shell brand"><div class="brand-mark">S+</div><div><p class="eyebrow">Security+ Practice Lab</p><h1>SY0-701 • Practice Exam</h1></div></div></header><div class="shell"><section class="hero"><p class="eyebrow">Practice responsibly</p><h2>Test your knowledge in an exam-style format and learn from every mistake.</h2><p>A bank of 1,000 original Security+-style questions — no exam dumps, with clear explanations for every answer.</p></section><section class="setup"><div class="card"><h3>Choose your mode</h3><div class="mode-grid"><button class="mode ${state.mode==='exam'?'selected':''}" data-mode="exam"><strong>Practice exam</strong><span>90 questions • 90 minutes • score and review at the end</span></button><button class="mode ${state.mode==='study'?'selected':''}" data-mode="study"><strong>Study mode</strong><span>Instant feedback and no time limit</span></button><button class="mode ${state.mode==='glossary'?'selected':''}" data-mode="glossary"><strong>Glossary</strong><span>Search Security+ acronyms and core concepts</span></button></div><div class="actions"><span class="progress-label">1,000-question bank • 90+ glossary entries</span><button class="primary" id="start">${state.mode==='glossary'?'Open glossary':`Start ${state.mode==='exam'?'exam':'studying'} →`}</button></div></div><aside class="card facts"><div class="fact"><b>90</b>questions per mock exam</div><div class="fact"><b>90 min</b>simulation time limit</div><div class="fact"><b>750 / 900</b>official passing benchmark*</div><div><h3>Domain blueprint</h3><div class="domain-list">${Object.values(DOMAINS).map(d=>`<div>${d.name}<br><b>${d.weight}%</b></div>`).join('')}</div></div></aside></section><p class="notice">* CompTIA uses scaled scoring, not a direct percentage. This tool provides an estimated readiness score only and is not affiliated with CompTIA.</p></div>`;
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;renderHome();}); $('#start').onclick=start;
}
function start(){ if(state.mode==='glossary'){renderGlossary();return;} state.index=0;state.answers={};state.flags={};state.submitted=false;state.remaining=5400;const targets={general:11,threats:20,architecture:16,operations:25,management:18};state.questions=Object.entries(targets).flatMap(([domain,count])=>[...ENGLISH_BANK].filter(q=>q.domain===domain).sort(()=>Math.random()-.5).slice(0,count)).sort(()=>Math.random()-.5);state.started=true; if(state.mode==='exam') state.timer=setInterval(()=>{state.remaining--;if(state.remaining<=0) submit();else renderExam();},1000); renderExam(); }
function renderGlossary(){
  const draw=(query='',domain='All')=>{const terms=GLOSSARY.filter(x=>(domain==='All'||x.domain===domain)&&`${x.term} ${x.definition}`.toLowerCase().includes(query.toLowerCase()));$('#glossary-list').innerHTML=terms.length?terms.map(x=>`<article class="review-item"><span class="domain-tag">${x.domain}</span><h3>${escapeHtml(x.term)}</h3><p>${escapeHtml(x.definition)}</p></article>`).join(''):'<p>No matching terms found.</p>';$('#glossary-count').textContent=`${terms.length} terms`};
  $('#app').innerHTML=`<header class="top"><div class="shell brand"><div class="brand-mark">S+</div><div><p class="eyebrow">Security+ Practice Lab</p><h1>Glossary</h1></div></div></header><div class="shell"><section class="hero"><p class="eyebrow">Study reference</p><h2>Security+ acronyms and concepts.</h2><p>Search the core vocabulary used in the practice questions and the SY0-701 objectives.</p></section><section class="card"><div class="actions"><div><h3 style="margin-bottom:0">Search the glossary</h3><p class="progress-label" id="glossary-count"></p></div><button class="secondary" id="home">← Back to home</button></div><div class="pbq-grid"><div class="pbq-row"><label for="glossary-search">Term or keyword</label><input id="glossary-search" type="search" placeholder="e.g. MFA, firewall, risk" style="width:100%;padding:9px;border:1px solid #b8c9d9;border-radius:7px" /></div><div class="pbq-row"><label for="glossary-domain">Domain</label><select id="glossary-domain"><option>All</option><option>General</option><option>Threats</option><option>Architecture</option><option>Operations</option><option>Management</option></select></div></div><div id="glossary-list"></div></section></div>`;
  const update=()=>draw($('#glossary-search').value,$('#glossary-domain').value);$('#glossary-search').oninput=update;$('#glossary-domain').onchange=update;$('#home').onclick=()=>{state.mode='exam';renderHome();};draw();
}
function answered(q){const a=state.answers[q.id];return q.type==='pbq'?a&&Object.keys(a).length===q.fields.length:Array.isArray(a)&&a.length>0;}
function choiceText(q,arr){if(!arr||!arr.length)return 'No answer';return arr.map(i=>`${letters[i]}. ${q.options[i]}`).join('; ');}
function isCorrect(q){const a=state.answers[q.id];if(q.type==='pbq')return a&&q.fields.every((f,i)=>Number(a[i])===f.correct);return a&&a.length===q.correct.length&&a.every(x=>q.correct.includes(x));}
function setChoice(q, idx, checked){let a=state.answers[q.id]||[]; if(q.multi){a=checked?[...new Set([...a,idx])]:a.filter(x=>x!==idx);}else a=checked?[idx]:[];state.answers[q.id]=a;save();renderExam();}
function save(){localStorage.setItem('securityplus-progress',JSON.stringify({answers:state.answers,flags:state.flags,index:state.index,remaining:state.remaining}));}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function renderQuestion(q){
 const reveal=state.mode==='study'&&answered(q); let choices='';
 if(q.type==='pbq'){const a=state.answers[q.id]||{};choices=`<p class="instruction">Choose an answer for every part of the scenario.</p><div class="pbq-grid">${q.fields.map((f,i)=>`<div class="pbq-row"><label>${f.label}</label><select data-pbq="${i}" ${reveal?'disabled':''}><option value="">— choose —</option>${f.options.map((o,x)=>`<option value="${x}" ${String(a[i])===String(x)?'selected':''}>${o}</option>`).join('')}</select></div>`).join('')}</div>`;}
 else {choices=`<p class="instruction">${q.multi?'Select all correct answers.':'Select the single best answer.'}</p>${q.options.map((o,i)=>{const chosen=(state.answers[q.id]||[]).includes(i);let cl='choice';if(reveal&&q.correct.includes(i))cl+=' correct';else if(reveal&&chosen)cl+=' wrong';return `<label class="${cl}"><input type="${q.multi?'checkbox':'radio'}" name="answer" value="${i}" ${chosen?'checked':''} ${reveal?'disabled':''}/><span class="letter">${letters[i]}</span><span>${escapeHtml(o)}</span></label>`;}).join('')}`;}
 let feedback='';if(reveal){feedback=`<div class="feedback ${isCorrect(q)?'good':'bad'}"><strong>${isCorrect(q)?'✓ Correct':'✕ Review the answer'}</strong><span>${q.type==='pbq'?'Every field must be selected correctly.':`Correct answer: ${choiceText(q,q.correct)}. `}${escapeHtml(q.explanation)}</span></div>`;}
 return `<span class="domain-tag">${DOMAINS[q.domain].name}</span><span class="type-tag">${q.type==='pbq'?'PBQ – performance-based question':q.multi?'Multiple response':'Multiple choice'}</span><p class="stem">${escapeHtml(q.stem)}</p>${choices}${feedback}`;
}
function renderExam(){ if(!state.started||state.submitted)return; const q=state.questions[state.index], done=Object.values(state.answers).filter(a=>a&&(Array.isArray(a)?a.length:Object.keys(a).length)).length; const pct=(state.index+1)/state.questions.length*100;
 $('#app').innerHTML=`<header class="top"><div class="shell brand"><div class="brand-mark">S+</div><div><p class="eyebrow">${state.mode==='exam'?'Practice exam':'Study mode'}</p><h1>Security+ SY0-701</h1></div><div class="timer ${state.remaining<300?'urgent':''}">${state.mode==='exam'?'⏱ '+formatTime(state.remaining):'✦ no time limit'}</div></div></header><div class="shell"><div class="exam-head"><div><b>Question ${state.index+1} of ${state.questions.length}</b><div class="bar"><i style="width:${pct}%"></i></div></div><span class="progress-label">Answered: ${done}/${state.questions.length}</span></div><div class="exam-layout"><section class="card question">${renderQuestion(q)}<div class="actions"><div class="action-group"><button class="secondary" id="prev" ${state.index===0?'disabled':''}>← Previous</button><button class="secondary" id="flag">${state.flags[q.id]?'★ Flagged':'☆ Flag'}</button></div><div class="action-group"><button class="danger" id="finish">Finish</button><button class="primary" id="next">${state.index===state.questions.length-1?'Submit exam':'Next →'}</button></div></div></section><aside class="card side-card"><b>Question palette</b><div class="palette">${state.questions.map((x,i)=>`<button data-go="${i}" class="${i===state.index?'current':''} ${answered(x)?'answered':''} ${state.flags[x.id]?'flagged':''}">${i+1}</button>`).join('')}</div><div class="legend">Green: answered • yellow bar: flagged</div></aside></div></div>`;
 document.querySelectorAll('input[name="answer"]').forEach(el=>el.onchange=e=>setChoice(q,+e.target.value,e.target.checked));document.querySelectorAll('[data-pbq]').forEach(el=>el.onchange=e=>{state.answers[q.id]??={};state.answers[q.id][e.target.dataset.pbq]=e.target.value;save();renderExam();});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.index=+b.dataset.go;save();renderExam();});$('#prev').onclick=()=>{state.index--;renderExam();};$('#next').onclick=()=>{if(state.index===state.questions.length-1)submit();else{state.index++;renderExam();}};$('#flag').onclick=()=>{state.flags[q.id]=!state.flags[q.id];save();renderExam();};$('#finish').onclick=()=>{if(confirm('Finish and see your result?'))submit();};
}
function submit(){clearInterval(state.timer);state.submitted=true;localStorage.removeItem('securityplus-progress');renderResults();}
function renderResults(){const correct=state.questions.filter(isCorrect).length, percent=Math.round(correct/state.questions.length*100), estimate=Math.round(100+percent*8), pass=estimate>=750; const byDomain=Object.entries(DOMAINS).map(([key,d])=>{const qs=state.questions.filter(x=>x.domain===key),n=qs.filter(isCorrect).length;return {d,n,total:qs.length,p:Math.round(n/qs.length*100)};}); const wrong=state.questions.filter(q=>!isCorrect(q)); $('#app').innerHTML=`<header class="top"><div class="shell brand"><div class="brand-mark">S+</div><div><p class="eyebrow">Practice result</p><h1>Security+ Practice Lab</h1></div></div></header><div class="shell"><section class="result-hero"><p class="eyebrow">${pass?'Estimated: ready to schedule your exam':'More study is recommended before taking the exam'}</p><div class="result-score">${percent}%</div><p>${correct} of ${state.questions.length} answers correct</p><div class="result-grid"><div class="metric"><b>~${estimate} / 900</b>estimated scaled score</div><div class="metric"><b>${pass?'≥ 750':'< 750'}</b>passing benchmark</div><div class="metric"><b>${wrong.length}</b>questions to review</div></div></section><section class="domain-results">${byDomain.map(x=>`<div class="domain-result"><strong><span>${x.d.name}</span><span>${x.p}%</span></strong><div class="bar"><i style="width:${x.p}%"></i></div><small>${x.n} / ${x.total} correct</small></div>`).join('')}</section><section class="card" style="margin-top:20px"><div class="actions"><div><h2 style="font-size:1.45rem;margin-bottom:0">Answer review</h2><p class="progress-label">Every missed item includes the correct answer and an explanation.</p></div><button class="primary" id="again">New attempt</button></div>${wrong.length?wrong.map(q=>`<article class="review-item"><span class="domain-tag">${DOMAINS[q.domain].name}</span><h3>${escapeHtml(q.stem)}</h3><p class="your-answer">Your answer: ${q.type==='pbq'?'Incomplete or incorrect PBQ response':choiceText(q,state.answers[q.id])}</p><p class="answer">Correct answer: ${q.type==='pbq'?'All selections must match the scenario':choiceText(q,q.correct)}</p><p>${escapeHtml(q.explanation)}</p></article>`).join(''):'<p>Excellent — every answer was correct.</p>'}</section></div>`;$('#again').onclick=()=>{state.mode='exam';renderHome();};}
renderHome();

