const state = { mode:'exam', index:0, answers:{}, flags:{}, started:false, submitted:false, remaining:5400, timer:null, questions:[...BANK] };
const $ = (s) => document.querySelector(s);
const letters = ['A','B','C','D','E','F'];
function escapeHtml(s){ return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function renderHome(){
  clearInterval(state.timer); state.started=false;
  $('#app').innerHTML = `<header class="top"><div class="shell brand"><div class="brand-mark">S+</div><div><p class="eyebrow">Security+ Practice Lab</p><h1>SY0-701 • próbny egzamin</h1></div></div></header><div class="shell"><section class="hero"><p class="eyebrow">Trenuj odpowiedzialnie</p><h2>Sprawdź wiedzę jak na egzaminie, ucz się z każdego błędu.</h2><p>Autorska baza pytań w formacie zbliżonym do Security+ — bez dumpów, za to z uzasadnieniem każdej odpowiedzi.</p></section><section class="setup"><div class="card"><h3>Wybierz tryb</h3><div class="mode-grid"><button class="mode ${state.mode==='exam'?'selected':''}" data-mode="exam"><strong>Egzamin próbny</strong><span>90 pytań • 90 minut • wynik i przegląd na końcu</span></button><button class="mode ${state.mode==='study'?'selected':''}" data-mode="study"><strong>Tryb nauki</strong><span>Natychmiastowa informacja zwrotna i bez limitu czasu</span></button></div><div class="actions"><span class="progress-label">Postęp jest zapisywany lokalnie w tej przeglądarce.</span><button class="primary" id="start">Rozpocznij ${state.mode==='exam'?'egzamin':'naukę'} →</button></div></div><aside class="card facts"><div class="fact"><b>90</b>maksymalna liczba pytań</div><div class="fact"><b>90 min</b>limit w symulacji</div><div class="fact"><b>750 / 900</b>oficjalny wynik zaliczający*</div><div><h3>Plan domen</h3><div class="domain-list">${Object.values(DOMAINS).map(d=>`<div>${d.name}<br><b>${d.weight}%</b></div>`).join('')}</div></div></aside></section><p class="notice">* Wynik CompTIA jest skalowany i nie jest prostym procentem. Ta aplikacja podaje wyłącznie szacunkową gotowość. Nie jest powiązana z CompTIA.</p></div>`;
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;renderHome();}); $('#start').onclick=start;
}
function start(){ state.index=0;state.answers={};state.flags={};state.submitted=false;state.remaining=5400;state.questions=[...BANK].sort(()=>Math.random()-.5);state.started=true; if(state.mode==='exam') state.timer=setInterval(()=>{state.remaining--;if(state.remaining<=0) submit();else renderExam();},1000); renderExam(); }
function answered(q){const a=state.answers[q.id];return q.type==='pbq'?a&&Object.keys(a).length===q.fields.length:Array.isArray(a)&&a.length>0;}
function choiceText(q,arr){if(!arr||!arr.length)return 'Brak odpowiedzi';return arr.map(i=>`${letters[i]}. ${q.options[i]}`).join('; ');}
function isCorrect(q){const a=state.answers[q.id];if(q.type==='pbq')return a&&q.fields.every((f,i)=>Number(a[i])===f.correct);return a&&a.length===q.correct.length&&a.every(x=>q.correct.includes(x));}
function setChoice(q, idx, checked){let a=state.answers[q.id]||[]; if(q.multi){a=checked?[...new Set([...a,idx])]:a.filter(x=>x!==idx);}else a=checked?[idx]:[];state.answers[q.id]=a;save();renderExam();}
function save(){localStorage.setItem('securityplus-progress',JSON.stringify({answers:state.answers,flags:state.flags,index:state.index,remaining:state.remaining}));}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function renderQuestion(q){
 const reveal=state.mode==='study'&&answered(q); let choices='';
 if(q.type==='pbq'){const a=state.answers[q.id]||{};choices=`<p class="instruction">Wybierz odpowiedź dla każdego elementu scenariusza.</p><div class="pbq-grid">${q.fields.map((f,i)=>`<div class="pbq-row"><label>${f.label}</label><select data-pbq="${i}" ${reveal?'disabled':''}><option value="">— wybierz —</option>${f.options.map((o,x)=>`<option value="${x}" ${String(a[i])===String(x)?'selected':''}>${o}</option>`).join('')}</select></div>`).join('')}</div>`;}
 else {choices=`<p class="instruction">${q.multi?'Wybierz wszystkie właściwe odpowiedzi.':'Wybierz jedną najlepszą odpowiedź.'}</p>${q.options.map((o,i)=>{const chosen=(state.answers[q.id]||[]).includes(i);let cl='choice';if(reveal&&q.correct.includes(i))cl+=' correct';else if(reveal&&chosen)cl+=' wrong';return `<label class="${cl}"><input type="${q.multi?'checkbox':'radio'}" name="answer" value="${i}" ${chosen?'checked':''} ${reveal?'disabled':''}/><span class="letter">${letters[i]}</span><span>${escapeHtml(o)}</span></label>`;}).join('')}`;}
 let feedback='';if(reveal){feedback=`<div class="feedback ${isCorrect(q)?'good':'bad'}"><strong>${isCorrect(q)?'✓ Poprawnie':'✕ Sprawdź odpowiedź'}</strong><span>${q.type==='pbq'?'Wymagane poprawne wybory dla wszystkich pól.':`Właściwa odpowiedź: ${choiceText(q,q.correct)}. `}${escapeHtml(q.explanation)}</span></div>`;}
 return `<span class="domain-tag">${DOMAINS[q.domain].name}</span><span class="type-tag">${q.type==='pbq'?'PBQ – zadanie praktyczne':q.multi?'Wielokrotny wybór':'Jednokrotny wybór'}</span><p class="stem">${escapeHtml(q.stem)}</p>${choices}${feedback}`;
}
function renderExam(){ if(!state.started||state.submitted)return; const q=state.questions[state.index], done=Object.values(state.answers).filter(a=>a&&(Array.isArray(a)?a.length:Object.keys(a).length)).length; const pct=(state.index+1)/state.questions.length*100;
 $('#app').innerHTML=`<header class="top"><div class="shell brand"><div class="brand-mark">S+</div><div><p class="eyebrow">${state.mode==='exam'?'Egzamin próbny':'Tryb nauki'}</p><h1>Security+ SY0-701</h1></div><div class="timer ${state.remaining<300?'urgent':''}">${state.mode==='exam'?'⏱ '+formatTime(state.remaining):'✦ bez limitu'}</div></div></header><div class="shell"><div class="exam-head"><div><b>Pytanie ${state.index+1} z ${state.questions.length}</b><div class="bar"><i style="width:${pct}%"></i></div></div><span class="progress-label">Udzielono odpowiedzi: ${done}/${state.questions.length}</span></div><div class="exam-layout"><section class="card question">${renderQuestion(q)}<div class="actions"><div class="action-group"><button class="secondary" id="prev" ${state.index===0?'disabled':''}>← Wstecz</button><button class="secondary" id="flag">${state.flags[q.id]?'★ Oznaczone':'☆ Oznacz'}</button></div><div class="action-group"><button class="danger" id="finish">Zakończ</button><button class="primary" id="next">${state.index===state.questions.length-1?'Oddaj egzamin':'Dalej →'}</button></div></div></section><aside class="card side-card"><b>Paleta pytań</b><div class="palette">${state.questions.map((x,i)=>`<button data-go="${i}" class="${i===state.index?'current':''} ${answered(x)?'answered':''} ${state.flags[x.id]?'flagged':''}">${i+1}</button>`).join('')}</div><div class="legend">Zielone: odpowiedź • żółta kreska: oznaczone</div></aside></div></div>`;
 document.querySelectorAll('input[name="answer"]').forEach(el=>el.onchange=e=>setChoice(q,+e.target.value,e.target.checked));document.querySelectorAll('[data-pbq]').forEach(el=>el.onchange=e=>{state.answers[q.id]??={};state.answers[q.id][e.target.dataset.pbq]=e.target.value;save();renderExam();});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.index=+b.dataset.go;save();renderExam();});$('#prev').onclick=()=>{state.index--;renderExam();};$('#next').onclick=()=>{if(state.index===state.questions.length-1)submit();else{state.index++;renderExam();}};$('#flag').onclick=()=>{state.flags[q.id]=!state.flags[q.id];save();renderExam();};$('#finish').onclick=()=>{if(confirm('Zakończyć i zobaczyć wynik?'))submit();};
}
function submit(){clearInterval(state.timer);state.submitted=true;localStorage.removeItem('securityplus-progress');renderResults();}
function renderResults(){const correct=state.questions.filter(isCorrect).length, percent=Math.round(correct/state.questions.length*100), estimate=Math.round(100+percent*8), pass=estimate>=750; const byDomain=Object.entries(DOMAINS).map(([key,d])=>{const qs=state.questions.filter(x=>x.domain===key),n=qs.filter(isCorrect).length;return {d,n,total:qs.length,p:Math.round(n/qs.length*100)};}); const wrong=state.questions.filter(q=>!isCorrect(q)); $('#app').innerHTML=`<header class="top"><div class="shell brand"><div class="brand-mark">S+</div><div><p class="eyebrow">Wynik próby</p><h1>Security+ Practice Lab</h1></div></div></header><div class="shell"><section class="result-hero"><p class="eyebrow">${pass?'Szacunkowo: gotowy/gotowa do podejścia':'Warto uzupełnić wiedzę przed podejściem'}</p><div class="result-score">${percent}%</div><p>${correct} z ${state.questions.length} odpowiedzi poprawnych</p><div class="result-grid"><div class="metric"><b>~${estimate} / 900</b>orientacyjny wynik skalowany</div><div class="metric"><b>${pass?'≥ 750':'< 750'}</b>próg referencyjny</div><div class="metric"><b>${wrong.length}</b>pytań do powtórki</div></div></section><section class="domain-results">${byDomain.map(x=>`<div class="domain-result"><strong><span>${x.d.name}</span><span>${x.p}%</span></strong><div class="bar"><i style="width:${x.p}%"></i></div><small>${x.n} / ${x.total} poprawnych</small></div>`).join('')}</section><section class="card" style="margin-top:20px"><div class="actions"><div><h2 style="font-size:1.45rem;margin-bottom:0">Przegląd odpowiedzi</h2><p class="progress-label">Każda pomyłka zawiera poprawną odpowiedź i wyjaśnienie.</p></div><button class="primary" id="again">Nowa próba</button></div>${wrong.length?wrong.map(q=>`<article class="review-item"><span class="domain-tag">${DOMAINS[q.domain].name}</span><h3>${escapeHtml(q.stem)}</h3><p class="your-answer">Twoja odpowiedź: ${q.type==='pbq'?'Niepełne lub błędne wykonanie PBQ':choiceText(q,state.answers[q.id])}</p><p class="answer">Poprawna odpowiedź: ${q.type==='pbq'?'Wszystkie wybory zgodne ze scenariuszem':choiceText(q,q.correct)}</p><p>${escapeHtml(q.explanation)}</p></article>`).join(''):'<p>Świetnie — wszystkie odpowiedzi są poprawne.</p>'}</section></div>`;$('#again').onclick=()=>{state.mode='exam';renderHome();};}
renderHome();

